#
# Copyright (c) 2019, Arm Limited and Contributors. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#

BS_LIB_NAME := eventhandler
BS_LIB_SOURCES := mod_eventhandler.c

include $(BS_DIR)/lib.mk
